### ISSUE TITLE
More Config Options

### ISSUE THREAD

**Issue by arboriginal** [ImCoolYeah105/CaveBiomes#1]
Hi ImCoolYeah,

I discovered your datapack today, watching a video of a well know french Youtuber:
https://youtu.be/-jt7OcgAel4

I'm agree with what he said in it (and lot of comments in the video tell the same), it seems to be a wonderful datapack but... the fact you include spawners in it will discourage some users to add it, especially in servers because it can be considered as "cheat" or gameplay breaker.

For example:
- the fact you can find Blaze mobs in overworld remove the need to go in Nether
- having several close spawners allows to create huge farms
- (not sure about this one) chests you add in your datapacks may be not wanted by server owners

I'm not familiar with datapacks (I create plugins instead) so I'm not sure you can create options in it, so maybe you should create 2 versions of your datapack: One without those points and one with. Or much better IMHO if possible, split it to let users install separately your spawners / chests addition.

IMHO, the true interest of your datapack is the cave biome generation (thx captain obvious) not those side structures, so I suggest to focus on it and not to force to have them in the same package.

BTW, for now I didn't complete my own tests so I can't say if all is working fine, but I already seen something which is a bit annoying for server owners (but not specific to your resource pack). Console is spammed by error message when it generates like this one:

« Block at 288, 4, 0 is Block{minecraft:stone} but has net.minecraft.server.v1_15_R1.TileEntityStructure@1a9c1766. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover. »

This doesn't break anything but when a plugin / datapack spam the console, you can be sure a majority of users will prefer to remove it. Shame! They'll miss out interesting resources... but that's a fact.

TBH, if after my tests I like the generation, I'll probably add a modified version where I'll remove listed parts. I know I can do it because it's under MIT licence but I would prefer to use an official version instead and focus on my other projects.

I hope to be clear in what I said, if not I'll develop my explanations.
Anyway, thanks for the sharing, and keep up the good work!

**Edit:** I'll add other things I think impacting the gameplay / causing potential problems while discovering it

- (minor) end rods, glowstones, nether warts in caves, and obviously end blocks, soul sand & netherrack, magma cubes but lower impact
[instead of listing each of them, I let you decide but you got the idea: end rods / glowstone are often re-searched for cosmetic reasons and nether warts farmed for potion so finding them without having to go in nether breaks a bit the gameplay]
- (more minor than minor...) sometimes, underground trees sometimes have their base block replaced by a flower.
- (multiplayer) lot of servers avoid the use of command blocks, I've seen structure air_dungeon for example create one and so, it can be inactive... Don't know what importance it has.

**Comment by ICY105** [comment]
1.1.0 added [config](https://github.com/ImCoolYeah105/CaveBiomes/wiki/Config) options to the datapack- right now it can only change biome weight/height (which you can use to disable biomes you don't want), but I can see more options being added like disabling dungeons/spawners.

Most of the spawners in the pack have been nerfed, and are 2-3 times slower than vanilla spawners with half the required player range. Some (like blazes and wither skeles) have had their loot tables removed so they don't drop anything.

The use of command blocks is to randomize dungeon rooms (otherwise every dungeon/village would be exactly the same).

**Comment by arboriginal** [comment]
Thanks for the details, I didn't see there is a possibility to configure it.
To people who will read this issue later, here is how to:
https://github.com/ImCoolYeah105/CaveBiomes/wiki/Config
I'll check it when I'll have more time.

About spawners, I'll wait you add option to disable them, even if nerfed. About command blocks, I suppose I have never generated a single dungeon then as I only see one by manually load the structure.

Thanks again for your time, to reply here but above all to share your projects.

**Comment by ICY105** [comment]
Added config options to disable spawners in caves, custom dungeons, and underground villages in 1.1.0c.
