### ISSUE TITLE
Buggy End generation

### ISSUE THREAD

**Issue by Noctree** [ImCoolYeah105/CaveBiomes#6]
Installed datapacks:
    - CaveBiomes (1.1.2)
    - DatapackUtilities (2.2.0)
![2020-07-28_19 31 15](https://user-images.githubusercontent.com/17685682/88700603-3908a480-d109-11ea-99a8-f1752bf43444.png)

Running on modded Fabric 1.16.1 client in singleplayer

The datapack is amazing, but it makes a mess in End.
It would also be nice to have a config option to disable generation in Nether as it interferes with other world generation mods

The End (main island):
![2020-07-28_19 32 43](https://user-images.githubusercontent.com/17685682/88700670-4de53800-d109-11ea-9a09-77cb9fbf5abb.png)

**Comment by ICY105** [comment]
Dangit, completely forgot to fix that. I knew it was an issue too -_-

**Comment by ICY105** [comment]
Fixed in 1.1.2a
