### ISSUE TITLE
Liquids and falling blocks repeatedly flicker often when generating.

### ISSUE THREAD

**Issue by slidedrum** [ImCoolYeah105/CaveBiomes#7]
Bug Report Template (you can altar this if you know what you're doing):
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
 - CaveBiomesConfig_v1.2.0
 - DatapackUtilities_v2.3.2b
 - cavebiomes-v1-2-0

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![image](https://user-images.githubusercontent.com/14340641/131247600-268b61af-7e7f-4a7b-9f07-f3e714b4fc20.png)

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
 - fabric-installer-0.7.4.jar with 0 mods loaded
 - running on a server
 - minecraft 1.17.1

4. What if happening vs. what you expect to happen?
 - Here is a video of the issue [https://streamable.com/tpvwpg](https://streamable.com/tpvwpg)
 - I move around after a bit to show how common it is, I did not know where any other issues where in the world other than the one where I started the recording.
 - I would expect it to eventually settle down and not continually make the server say it can't keep up
![image](https://user-images.githubusercontent.com/14340641/131247720-6dac61cf-d751-44db-bd8b-b89fa6a6ea55.png)

**Comment by ICY105** [comment]
Well apparently the issue I thought I fixed in 2.3.2b isn't actually fixed. This is very annoying.

**Comment by ICY105** [comment]
Actually this is a seperate, much simplier issue (phew).
I'll release a patch but for now just run the command /gamerule maxCommandChainLength 1000000000
